### ISSUE TITLE
panic: $HOME is not defined when running as process using supervisord

### ISSUE THREAD

**Issue by khanakia** [apple/pkl-go#45]
I am trying to run my binary as process using http://supervisord.org/running.html and getting below error

Why pkl need to look for the home directory ?

```
panic: $HOME is not defined

goroutine 1 [running]:
github.com/apple/pkl-go/pkl.init.func4(0xc0000215e0)
	/home/test/html/prod/myproj/vendor/github.com/apple/pkl-go/pkl/evaluator_options.go:250 +0xab
github.com/apple/pkl-go/pkl.init.func11(0xc0000215e0)
	/home/test/html/prod/myproj/vendor/github.com/apple/pkl-go/pkl/evaluator_options.go:349 +0x56
github.com/apple/pkl-go/pkl.buildEvaluatorOptions({0xc0002dd0e0, 0x1, 0xc0001588a0?})
	/home/test/html/prod/myproj/vendor/github.com/apple/pkl-go/pkl/evaluator_options.go:228 +0x44
github.com/apple/pkl-go/pkl.(*evaluatorManager).NewEvaluator(0xc0002e6ec0, {0x181d230, 0x22bd9c0}, {0xc0002dd0e0, 0x1, 0x1})
	/home/test/html/prod/myproj/vendor/github.com/apple/pkl-go/pkl/evaluator_manager.go:96 +0x16e
github.com/apple/pkl-go/pkl.NewEvaluatorWithCommand({0x181d230, 0x22bd9c0}, {0x0?, 0xc00046bb60?, 0xc00043ca98?}, {0xc0002dd0e0, 0x1, 0x1})
	/home/test/html/prod/myproj/vendor/github.com/apple/pkl-go/pkl/evaluator_exec.go:85 +0x7c
github.com/apple/pkl-go/pkl.NewEvaluator(...)
	/home/test/html/prod/myproj/vendor/github.com/apple/pkl-go/pkl/evaluator_exec.go:26
configmgr/gen/appconfig.LoadFromPath({0x181d230, 0x22bd9c0}, {0x15fc732, 0x1d})
	/home/test/html/prod/myproj/configmgr/gen/appconfig/AppConfig.pkl.go:35 +0xa8
configmgr.GetAppConfig()
```

```go
package configmgr

import (
	"configmgr/gen/appconfig"
	"configmgr/gen/cacheconfig"
	"context"
	"fmt"
)

func GetAppConfig() *appconfig.AppConfig {
	cfg, err := appconfig.LoadFromPath(context.Background(), "../config/pkl/default/app.pkl")
	fmt.Println(cfg)
	if err != nil {
		panic(err)
	}
	return cfg
}
```

**Comment by bioball** [comment]
This is expected behavior; `LoadFromPath` will create an evaluator with preconfigured options, and that will panic if the home dir is not set because it can't determine what the cache dir is.

What you can do instead is create your own evaluator, and use `Load()` instead.
When creating the evaluator, you can copy most of `PreconfiguredOptions`, but provide your own cache dir. For example:

```go
ev, err := pkl.NewEvaluator(context.Background(), func (opts) {
	pkl.WithDefaultAllowedResources(opts)
	pkl.WithOsEnv(opts)
	pkl.WithDefaultAllowedModules(opts)
	opts.CacheDir = "/path/to/my/cache/dir"
	opts.Logger = NoopLogger
})
if err != nil {
	panic(err)
}
cfg, err := appconfig.Load(context.Background(), ev, pkl.FileSource("../config/pkl/default/app.pkl"))
```

We should probably add a doc comment about the panic behavior in our generated code.

**Comment by khanakia** [comment]
I did another workaround. I passed the custom env variable as `HOME` in supervisor config and it worked.
